print("Welcome to the band name Generator")
city_name=input("What's the name of the city you grew up in?\n")
pet_name=input("What is the name of a pet?\n")
print("Your name band could be: "+city_name+" "+pet_name)
print("Your name band could be:",city_name+" "+pet_name)
